spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
